# Generated by Django 5.2.4 on 2025-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('ea', 'Each'), ('lb', 'Pound'), ('oz', 'Ounce'), ('kg', 'Kilogram')], default='ea', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How many in stock', max_digits=7),
        ),
    ]
